### ISSUE TITLE
OPTIFINE CRASHS

### ISSUE THREAD

**Issue by MelrikBirchJr** [Gollorum/Signpost#100]
it crashes after loading game then with not enough crashes it doesnt show what mod it is but ive been testing and its this mod specifically

**Comment by Gollorum** [comment]
This is actually an Optifine Bug: https://github.com/sp614x/optifine/issues/7127
On the newer forge versions, Optifine breaks any Mods that use .obj models, which Signpost does for the waystone variations. Try downgrading Forge to version 43.1.1, that's the one Optifine says it supports. That worked for me.
