### ISSUE TITLE
[Crash] 1.11.2 Crash when opening waystone gui

### ISSUE THREAD

**Issue by chameleoon** [Gollorum/Signpost#14]
Just tried the mod for the first time, I`ve right clicked the waystone and it worked but got distracted and exited the gui, after a few minutes got back to it but it crashed my client on right-click.

crash log:
https://pastebin.com/raw/Y6CBtbZq

**Comment by Gollorum** [comment]
Thank you :D 
I don't know what caused this, so I cannot be sure, but it should not happen again with the next version.

**Comment by Gollorum** [comment]
As the new Version is online now, I'll close this. If it happens again, just open a new issue.
