### ISSUE TITLE
other players kicked from server when renaming sign

### ISSUE THREAD

**Issue by Temil2006** [Gollorum/Signpost#18]
running a server with a few players. if anyone on the server places a sign down, seems fine. but when they right click it, type in the name, and Enter to save it.. all players (except for the player that did the renaming) is kicked out of the server. There is no crash report since it was only a server kick / drop and not a full crash.

tried newest new versions for 1.11.2 since 6/10/2017  with the same results.

not sure what else to provide.

**Comment by Gollorum** [comment]
Thanks :D
I found and solved the problem. I'll propably upload a fix later this evening.
