### ISSUE TITLE
Payments do not work?

### ISSUE THREAD

**Issue by Ash70** [Gollorum/Signpost#27]
MC 1.12.2
Version 1.05.5
Forge 2512

Unless I do something wrong, it seems like no payments are subtracted. I have set paymentItem=minecraft:gold_ingot  and when creating a signpost it says it will cost X Gold Ingots but when teleporting, no gold ingots are removed from my inventory?

[Here's my config file](https://pastebin.com/UagUaY2A).

**Comment by Gollorum** [comment]
Thank you for reporting the bug :D
The next version should fix it.

**Comment by Gollorum** [comment]
The new version is available now
