### ISSUE TITLE
OWNERS cannot place signposts

### ISSUE THREAD

**Issue by QuarterAnimal** [Gollorum/Signpost#28]
Is the omission of an OWNERS if-clause in ConfigHandler.SecurityLevel.canPlace() intentional? Without it, players can't seem to place them when signpostPermissionLevel=OWNERS. I presume the same is true of waystones.

**Comment by Gollorum** [comment]
You are absolutely right, I will change that with the next update.
Thank you :D

**Comment by Gollorum** [comment]
The new update is available now
