### ISSUE TITLE
Broken waystones item drop sometimes has no item texture

### ISSUE THREAD

**Issue by CplPibald** [Gollorum/Signpost#30]
Place a waystone with a model (not the full-block waystone) and immediately break it with an iron pickaxe.

The item you get back has the magenta+black checkered texture.  The broken items have metadata=3, which is causing it to have invalid item state.  The correctly rendering items have metadata 0.

**Comment by Gollorum** [comment]
Fixed with version 1.07.1
Thanks for reporting the bug :D
