### ISSUE TITLE
Server log spam "0 waystones saved"

### ISSUE THREAD

**Issue by CplPibald** [Gollorum/Signpost#31]
Dedicated server running **signpost-1.12-1.07**

    [Server thread/INFO] [signpost]: 0 waystones saved

Every 40 seconds or so this line outputs to the server log, and it fills up the log and console window making it harder to see other log messages.

Can you please either disable this log line, or add a config allowing server operators to suppress it in the server log and console?  Thank you.

**Comment by CplPibald** [comment]
Wow, it looks like this was already fixed in 406bc3d2 .  Nice job!

**Comment by CplPibald** [comment]
Can you please release a version of this mod with this change?   I don't see any updates on curseforge.

**Comment by Gollorum** [comment]
There is another bug I'd like to fix with the next update and I'm not at home right now. I'll try to release it next week, maybe tuesday or so.

**Comment by Gollorum** [comment]
The new version is released
