### ISSUE TITLE
Stderror in server log.

### ISSUE THREAD

**Issue by Jophire** [Gollorum/Signpost#32]
This error repeats whenever a player uses a signpost. Its nothing gamebreaking, but it does drown the server log with messages.

`[Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at java.lang.Thread.run(Thread.java:745)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: java.util.zip.ZipException: Not in GZIP format
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.modIntegration.WaystonesModHandler.getNotGlobalByAllPlayers(WaystonesModHandler.java:105)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.modIntegration.WaystonesModHandler.getAllBaseInfos(WaystonesModHandler.java:52)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.modIntegration.SignpostAdapter.getExternalBaseInfos(SignpostAdapter.java:37)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.management.PostHandler.getAllWaystones(PostHandler.java:506)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.management.PostHandler.getForceWSbyName(PostHandler.java:197)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.blocks.tiles.PostPostTile$2.run(PostPostTile.java:163)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at gollorum.signpost.SPEventHandler.onServerTick(SPEventHandler.java:111)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1339_SPEventHandler_onServerTick_TickEvent.invoke(.dynamic)
22:27:23  [Info] [STDERR]: [gollorum.signpost.modIntegration.WaystonesModHandler:getNotGlobalByAllPlayers:110]: at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)`

**Comment by Gollorum** [comment]
I disabled the error log with the new version (1.08).
Sorry for taking so long :)
