### ISSUE TITLE
2min logs - Gzip dynmap?

### ISSUE THREAD

**Issue by generrosity** [Gollorum/Signpost#33]
Every two minutes or so, it looks like signpost is generating errors.

Generally, the server console it quiet, then after someone activates a signpost (or just randomly??) it will generate these.

I can see references to gzip, and dynmap, "concurrent.FutureTask" - I do have tickdynamic running in the background too.

Appologies for the size of the log - its hard to see where to seperate it, that there are multiple different errors, or anything going on 😱😭

**Comment by generrosity** [comment]
Apparently the URL for the file wasn't attached. But I found the code, which is obviously a stacktrace, presumably for 

```
	private Set<BaseInfo> getNotGlobalByAllPlayers(){
   [....]
                              try{ [...]
						tagCompound = tagCompound.getCompoundTag("ForgeData").getCompoundTag("PlayerPersisted").getCompoundTag("Waystones");
						stream.close();
						Set<BaseInfo> bases = getNotGlobalByTagCompound(tagCompound);
						ret.addAll(bases);
					}catch(Exception e){e.printStackTrace();}
```

Would it be possible to change the trace to something that includes the PLAYER data item details? Or something about the stream? "java.util.zip.ZipException: Not in GZIP format" isn't solvable from the current information.

**Comment by generrosity** [comment]
Also confirming we are running the latest Beta version 👍

**Comment by Gollorum** [comment]
I disabled the error log with the new version (1.08).
Sorry for taking so long :)
