### ISSUE TITLE
NullPointerException in ServerTickEvent

### ISSUE THREAD

**Issue by LlubNek** [Gollorum/Signpost#40]
Got the following error.  One village had already generated, so this is probably when generating a second village, and filling in the signpost at the first village (was there a signpost? ...)

> Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@210724f3: java.lang.NullPointerException at gollorum.signpost.worldGen.villages.LibraryWaystoneHelper$1.run(LibraryWaystoneHelper.java:44) at gollorum.signpost.SPEventHandler.onServerTick(SPEventHandler.java:111) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4716_SPEventHandler_onServerTick_TickEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:745)

Minecraft 1.12.2
Forge 1.12.2-14.23.5.2837
Signpost 1.08.1

[crash-2019-05-11_09.01.04-server.txt](https://github.com/Gollorum/Signpost/files/3169060/crash-2019-05-11_09.01.04-server.txt)
[latest.log](https://github.com/Gollorum/Signpost/files/3169062/latest.log)

**Comment by Gollorum** [comment]
A fix for that is now online
Thank you :D
