### ISSUE TITLE
Waystones not craftable

### ISSUE THREAD

**Issue by tecrogue** [Gollorum/Signpost#42]
Even with the configuration set to be able to craft waystones, the recipe does not show up in JEI and they are not craftable.

[signpost.cfg.txt](https://github.com/Gollorum/Signpost/files/3259533/signpost.cfg.txt)

**Comment by Gollorum** [comment]
Hey, I just fixed this bug with the new version (1.08.3).
Thank you for reporting it :D
Sorry it took me so long, the past few moths have been stressful.
