### ISSUE TITLE
Request for a few features

### ISSUE THREAD

**Issue by mankra** [Gollorum/Signpost#5]
Really great mod so far, but it could get even better. ;-)

- [x] Add a question wether one wants to teleport or not.
- [x] Add ability to dye signs with different colors.
- [x] Add an option to center the names on the signs.
- [ ] Add posts made from logs.
- [ ] Integrate additional wood from mods like [Biomes O' Plenty](https://minecraft.curseforge.com/projects/biomes-o-plenty) etc.
- [ ] Integrate additional metals (Copper etc.) from mods like [Thermal Foundation](https://minecraft.curseforge.com/projects/thermal-foundation) etc.

**Comment by Gollorum** [comment]
Why do you think that the question you described would be necessary? Why would one right-click a signpost without wanting to teleport? I imagine it quite annoying, having to confirm the teleport every time.

**Comment by mankra** [comment]
I don't think it's necessary. I think it's a nice to have, especially when a paymentItem is set, to prevent wasting the item by clicking on the wrong sign (e.g. when in a hurry or brainafk). But it's okay if you don't want to support brainafk. ;-)

**Comment by Gollorum** [comment]
Since you can now paint posts and signs with any texture you like, I think this can finally be closed :D
