### ISSUE TITLE
Signpost crash on 1.08.4

### ISSUE THREAD

**Issue by happybandit360** [Gollorum/Signpost#52]
Signpost version - 1.12.2-1.08.4
Forge version - 14.23.5.2847

Attempting to use a signpost to travel cross dimension results in the client crashing to desktop. Multiple testers have reproduced this issue
- https://hatebin.com/ibzvhnbeoq
- https://hatebin.com/gmiwppkkpb
- https://hatebin.com/zfcvobhcew
- https://hastebin.com/eqenenexaw

We will be rolling back to the release build of 1.08.3, but wanted to let you know about the issue.

Issue report from one of our testers: https://github.com/JoelZBub/organic-free-range-pack/issues/21

**Comment by Gollorum** [comment]
Thank you for your elaborate bug report :D
I just uploaded version 1.08.5. The problem should be solved with this.
