### ISSUE TITLE
[1.11.2 v1.02] Crash when you break a signpost with bare hands

### ISSUE THREAD

**Issue by VallenFrostweaver** [Gollorum/Signpost#6]
In single player I broke a sign (that had a waystone assigned to it) with my empty hand and it crashed and I landed in the multiplayer menu. Upon re-entering the single player world it no longer allows entry and does the same again. NOT easy to reproduce.

**Comment by VallenFrostweaver** [comment]
EDIT: Starting another world I can't seem to reproduce it now. o.o

**Comment by Gollorum** [comment]
That's strange... Do you still have the error log?

**Comment by VallenFrostweaver** [comment]
No report was generated. So strange

**Comment by Gollorum** [comment]
Problem found and solved :D 
The next update should fix it.
