### ISSUE TITLE
[1.11.2 v1.02] Shift-left click with tool to "flip" sign does not work

### ISSUE THREAD

**Issue by VallenFrostweaver** [Gollorum/Signpost#7]
I am aware in creative it will break the sign but in non-creative it will try to eventually break the sign instead of "flipping" it to point the other way (which then leads to another issue already listed). Currently, it only allows the arrow to point in one direction though rotation still works fine.

**Comment by Gollorum** [comment]
Yes, I know that bug and I already found its cause. It will be fixed in the next update. It affects all left-click actions in the 1.9.4, 1.10.2 and 1.11.2 versions, so counter-rotation doesn't work too.
