### ISSUE TITLE
should people wait 1.16.5 version of this mod?

### ISSUE THREAD

**Issue by Nicknaem** [Gollorum/Signpost#82]
are you going to port it to 1.16.5 or you don't know it yet?

**Comment by Gollorum** [comment]
A new version for 1.16.5 and 1.17.1 is almost done and should be released soon ™
The only things left to do are some testing and bug fixing

**Comment by Nicknaem** [comment]
> A new version for 1.16.5 and 1.17.1 is almost done and should be released soon ™
> The only things left to do are some testing and bug fixing

Woohoo 🎉🎉🎉 thats awesome, thanks
