### ISSUE TITLE
Compatibility request with Repurposed Structures

### ISSUE THREAD

**Issue by TelepathicGrunt** [Gollorum/Signpost#94]
Hello! I am the dev for Repurposed Structures mod: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

I was looking into maybe making a compat datapacks for Signpost to spawn signposts in Repurposed Structures's villages. And example datapack would be here: https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-more-villagers-datapack

My mod basically has a system to read pool entries within the pool_additions folder and inject them into the corresponding pool by replacing pool_additions in the path with worldgen/tenplate_pool. I also have a rs_pieces_spawn_counts_additions folder for specifying maximum and minimum amount a piece should spawn. 

However, I noticed you added waystones compat so you have two different mods for your signposts. And I am not sure if your signposts would find my own villages with its signs.

I was wondering that instead of me making say two different datapacks, it may be better for the compat to be done within signpost while also using my json system to add the pieces to my villages. A perk of this way is you can register a condition to my special registry and use it in my json to be able to turn off and on the compat. The idea would be signpost registers 2 conditions. One for regular signposts. And 1 for waystone signposts. Have the pool entries for each use the right condition and you can now turn on and off which nbt file to use based on if waystones is on or not. 

Example registering `() -> true` to my condition registry: 
https://github.com/TelepathicGrunt/RepurposedStructures/blob/13d1fe78cca06d271991c356ff31c6d382a30d4f/src/main/java/com/telepathicgrunt/repurposedstructures/misc/structurepiececounter/JSONConditionsRegistry.java#L21

Example json from another mod using the conditions field: 
https://github.com/LordDeatHunter/FabricWaystones/blob/cc27f3391908954ff7a60f69abb33a1cd7c10a4d/src/main/resources/data/repurposed_structures/pool_additions/villages/birch/houses.json#L13
https://github.com/LordDeatHunter/FabricWaystones/blob/cc27f3391908954ff7a60f69abb33a1cd7c10a4d/src/main/resources/data/repurposed_structures/rs_pieces_spawn_counts_additions/village_birch.json#L7

If you like this idea but need help or get stuck, just let me know and I'll try and help out!

**Comment by Gollorum** [comment]
Added with version 2.01.0
