### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by Hikcs** [Gollorum/Signpost#96]
When I load the game, it stops and gives the following error.

![image](https://user-images.githubusercontent.com/72861624/182101639-4fefb8bb-9e1d-405a-932f-9cca650a6177.png)

Crash Report: [https://pastebin.com/sGtDAkut](url)

Thanks in advance.

**Comment by Gollorum** [comment]
Seems like forge version 41.1.0 changed things which made the mod break. I uploaded a fix, the new version should work
